# Generated by Django 5.1.2 on 2024-11-07 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='email',
            new_name='Clint_email',
        ),
    ]
