# Generated by Django 5.1.2 on 2024-11-07 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0002_rename_email_client_clint_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Clint_email',
            new_name='client_email',
        ),
    ]
