# Generated by Django 5.1.2 on 2024-11-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0003_rename_clint_email_client_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=None, max_length=4, unique=True, verbose_name='Order ID'),
        ),
    ]
