# Generated by Django 5.1.2 on 2024-11-08 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0004_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_plan',
        ),
        migrations.AddField(
            model_name='billing',
            name='client',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='userEx.client'),
        ),
        migrations.AddField(
            model_name='billing',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='userEx.order'),
        ),
        migrations.AddField(
            model_name='billing',
            name='service_plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userEx.serviceplan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userEx.client', verbose_name='Client ID *'),
        ),
    ]
