# Generated by Django 5.1.2 on 2024-11-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0005_remove_client_company_name_remove_order_billing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='name',
            field=models.CharField(choices=[('basic', 'Basic Plan'), ('normal', 'Normal Plan'), ('professional', 'Professional Plan'), ('premium', 'Premium Plan'), ('enterprise', 'Enterprise Plan')], default='basic', max_length=20, unique=True),
        ),
    ]
