# Generated by Django 5.1.2 on 2024-11-08 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0006_alter_serviceplan_description_alter_serviceplan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afterhoursholidaypremium',
            name='order',
        ),
        migrations.RemoveField(
            model_name='fastrakbriefcase',
            name='order',
        ),
        migrations.RemoveField(
            model_name='multilingualsupport',
            name='order',
        ),
        migrations.RemoveField(
            model_name='starterprosiwosoftwareservice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='technicalsupport',
            name='order',
        ),
        migrations.CreateModel(
            name='ServiceSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multilingual_support_agents', models.PositiveIntegerField(default=0)),
                ('after_hours_support_hours', models.PositiveIntegerField(default=0)),
                ('technical_support_hours', models.PositiveIntegerField(default=0)),
                ('fastrak_briefcase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('starter_prosiwo_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_selections', to='userEx.order')),
                ('service_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userEx.serviceplan')),
            ],
        ),
        migrations.DeleteModel(
            name='AddOnService',
        ),
        migrations.DeleteModel(
            name='AfterHoursHolidayPremium',
        ),
        migrations.DeleteModel(
            name='FasTrakBriefcase',
        ),
        migrations.DeleteModel(
            name='MultilingualSupport',
        ),
        migrations.DeleteModel(
            name='StarterProSIWOSoftwareService',
        ),
        migrations.DeleteModel(
            name='TechnicalSupport',
        ),
    ]
