# Generated by Django 5.1.2 on 2024-11-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0008_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
    ]
