# Generated by Django 5.1.2 on 2024-11-15 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0009_remove_document_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_agreed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('duration_from', models.DateField()),
                ('duration_to', models.DateField(blank=True, null=True)),
                ('key_responsibilities', models.TextField()),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='userEx.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('graduation_year', models.IntegerField()),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='userEx.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_info', to='userEx.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_interested', models.TextField()),
                ('strong_fit_reason', models.TextField()),
                ('eligible_to_work', models.BooleanField()),
                ('source_of_opportunity', models.CharField(choices=[('Referral', 'Referral'), ('Social Media', 'Social Media'), ('Job Portal', 'Job Portal'), ('Fastrak Connect Website', 'Fastrak Connect Website')], max_length=50)),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='userEx.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='MediaUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.FileField(upload_to='cover_letters/')),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_uploads', to='userEx.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='PositionInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_applied_for', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=20)),
                ('preferred_shift', models.CharField(blank=True, choices=[('Day', 'Day Shift'), ('Night', 'Night Shift')], max_length=20, null=True)),
                ('applied_date', models.DateField()),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position_info', to='userEx.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='SkillsAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(help_text='Comma-separated values', max_length=200)),
                ('tech_skills', models.CharField(help_text='Comma-separated values', max_length=200)),
                ('certificates', models.TextField(blank=True, null=True)),
                ('tech_experience_description', models.TextField()),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills_assessment', to='userEx.jobapplication')),
            ],
        ),
    ]
