# Generated by Django 5.1.2 on 2024-11-15 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0010_jobapplication_experience_education_basicinformation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinformation',
            name='job_application',
        ),
    ]
