# Generated by Django 5.1.2 on 2024-11-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0012_delete_basicinformation_remove_jobapplication_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediauploads',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='cover_letters/'),
        ),
        migrations.AlterField(
            model_name='mediauploads',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
