# Generated by Django 5.1.2 on 2024-11-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0013_alter_mediauploads_cover_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediauploads',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='applicant_videos/'),
        ),
    ]
