# Generated by Django 5.1.2 on 2024-11-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0015_alter_positioninformation_preferred_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
