# Generated by Django 5.1.2 on 2024-11-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0017_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_phone',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
