# Generated by Django 5.1.2 on 2024-11-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0018_alter_admin_admin_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
