# Generated by Django 5.1.2 on 2024-11-20 15:10

import userEx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0019_jobapplication_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediauploads',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to=userEx.models.MediaUploads.upload_to_path),
        ),
        migrations.AlterField(
            model_name='mediauploads',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=userEx.models.MediaUploads.upload_to_path),
        ),
        migrations.AlterField(
            model_name='mediauploads',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=userEx.models.MediaUploads.upload_to_path),
        ),
    ]
