# Generated by Django 5.1.2 on 2024-11-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0020_alter_mediauploads_cover_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='duration_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='key_responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
